import {
    type LucideIcon,
    Trash2,
    Plus,
    ArrowRight,
    ArrowLeft,
    Search,
    X,
    Check,
    AlertCircle,
    Info,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    CalendarDays,
    Menu,
    SlidersHorizontal,
    Gamepad2,
    Clock,
    DollarSign,
    Star,
    Library,
    Settings,
    Tag,
    Users,
    Activity,
    Loader,
} from "lucide-react";

export const iconRegistry = {
    trash: Trash2,
    plus: Plus,
    "arrow-right": ArrowRight,
    "arrow-left": ArrowLeft,
    search: Search,
    close: X,
    check: Check,
    alert: AlertCircle,
    info: Info,
    "chevron-down": ChevronDown,
    "chevron-up": ChevronUp,
    "chevron-left": ChevronLeft,
    "chevron-right": ChevronRight,
    calendar: CalendarDays,
    menu: Menu,
    sliders: SlidersHorizontal,
    gamepad: Gamepad2,
    clock: Clock,
    dollar: DollarSign,
    star: Star,
    library: Library,
    settings: Settings,
    tag: Tag,
    users: Users,
    activity: Activity,
    loader: Loader,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
