import bcrypt from "bcryptjs";
import { mongoClientPromise, mongoDisconnect } from "../src/services/mongo";
import { UserModel } from "../src/models/user/user.mongo";
import { AuthModel } from "../src/models/auth/auth.mongo";
import { UserLibraryModel } from "../src/models/user-library/user-library.mongo";

const CDN = "https://cdn.cloudflare.steamstatic.com/steam/apps";
const cover = (id: number) => `${CDN}/${id}/header.jpg`;

const DEMO_EMAIL = "demo@lucid.com";
const DEMO_PASSWORD = "lucid-demo";

const libraryGames = (userId: string) => [
    // --- Completed ---
    {
        user_id: userId,
        title: "Elden Ring",
        genre: "role-playing",
        platform: "playstation",
        status: "completed",
        favorite: true,
        hours_played: 120,
        rating: 4.9,
        price: "59.99",
        date_purchased: new Date("2022-02-25"),
        date_played: new Date("2022-03-01"),
        comment: "Masterpiece, best FromSoftware game.",
        cover_url: cover(1245620),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Hollow Knight",
        genre: "platform",
        platform: "PC",
        status: "completed",
        favorite: true,
        hours_played: 42,
        rating: 4.8,
        price: "14.99",
        date_purchased: new Date("2021-06-10"),
        date_played: new Date("2021-06-15"),
        comment: null,
        cover_url: cover(367520),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Hades",
        genre: "action",
        platform: "nintendo",
        status: "completed",
        favorite: true,
        hours_played: 80,
        rating: 4.7,
        price: "24.99",
        date_purchased: new Date("2021-09-17"),
        date_played: new Date("2021-09-20"),
        comment: null,
        cover_url: cover(1145360),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Stardew Valley",
        genre: "simulation",
        platform: "PC",
        status: "completed",
        favorite: true,
        hours_played: 90,
        rating: 4.8,
        price: "0.00",
        date_purchased: new Date("2020-05-10"),
        date_played: new Date("2020-05-12"),
        comment: "Incredibly relaxing.",
        cover_url: cover(413150),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "God of War",
        genre: "action",
        platform: "playstation",
        status: "completed",
        favorite: true,
        hours_played: 35,
        rating: 4.9,
        price: "49.99",
        date_purchased: new Date("2020-08-12"),
        date_played: new Date("2020-08-14"),
        comment: "One of the best stories in gaming.",
        cover_url: cover(1593500),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "The Last of Us Part I",
        genre: "action",
        platform: "playstation",
        status: "completed",
        favorite: true,
        hours_played: 15,
        rating: 5.0,
        price: "39.99",
        date_purchased: new Date("2022-09-02"),
        date_played: new Date("2022-09-03"),
        comment: "Perfect game.",
        cover_url: cover(1888930),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Portal 2",
        genre: "puzzle",
        platform: "PC",
        status: "completed",
        favorite: false,
        hours_played: 10,
        rating: 4.9,
        price: "9.99",
        date_purchased: new Date("2018-11-23"),
        date_played: new Date("2018-12-01"),
        comment: "Brilliantly designed.",
        cover_url: cover(620),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Red Dead Redemption 2",
        genre: "action",
        platform: "playstation",
        status: "completed",
        favorite: true,
        hours_played: 110,
        rating: 4.9,
        price: "39.99",
        date_purchased: new Date("2019-03-15"),
        date_played: new Date("2019-03-20"),
        comment: "Unmatched world building and story.",
        cover_url: cover(1174180),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Celeste",
        genre: "platform",
        platform: "nintendo",
        status: "completed",
        favorite: false,
        hours_played: 14,
        rating: 4.7,
        price: "19.99",
        date_purchased: new Date("2021-01-05"),
        date_played: new Date("2021-01-10"),
        comment: "Tight controls, great story.",
        cover_url: cover(504230),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Disco Elysium",
        genre: "role-playing",
        platform: "PC",
        status: "completed",
        favorite: false,
        hours_played: 40,
        rating: 4.6,
        price: "39.99",
        date_purchased: new Date("2021-04-01"),
        date_played: new Date("2021-04-05"),
        comment: "Most unique RPG I've played.",
        cover_url: cover(632470),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Playing ---
    {
        user_id: userId,
        title: "Baldur's Gate 3",
        genre: "role-playing",
        platform: "PC",
        status: "playing",
        favorite: false,
        hours_played: 35,
        rating: null,
        price: "59.99",
        date_purchased: new Date("2023-08-03"),
        date_played: new Date("2023-08-05"),
        comment: "Still going, incredible depth.",
        cover_url: cover(1086940),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "FIFA 25",
        genre: "sport",
        platform: "playstation",
        status: "playing",
        favorite: false,
        hours_played: 55,
        rating: 3.0,
        price: "69.99",
        date_purchased: new Date("2024-09-27"),
        date_played: new Date("2024-09-27"),
        comment: null,
        cover_url: cover(2669320),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Hades II",
        genre: "action",
        platform: "PC",
        status: "playing",
        favorite: false,
        hours_played: 12,
        rating: null,
        price: "24.99",
        date_purchased: new Date("2024-05-06"),
        date_played: new Date("2024-05-07"),
        comment: "Early access but already incredible.",
        cover_url: cover(1145350),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Mario Kart 8 Deluxe",
        genre: "racing",
        platform: "nintendo",
        status: "playing",
        favorite: false,
        hours_played: 28,
        rating: 4.3,
        price: "59.99",
        date_purchased: new Date("2023-12-25"),
        date_played: new Date("2023-12-25"),
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Forza Horizon 5",
        genre: "racing",
        platform: "xbox",
        status: "playing",
        favorite: false,
        hours_played: 22,
        rating: null,
        price: "59.99",
        date_purchased: new Date("2024-01-10"),
        date_played: new Date("2024-01-12"),
        comment: null,
        cover_url: cover(1551360),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Paused ---
    {
        user_id: userId,
        title: "Cyberpunk 2077",
        genre: "action",
        platform: "PC",
        status: "paused",
        favorite: false,
        hours_played: 18,
        rating: 3.5,
        price: "39.99",
        date_purchased: new Date("2022-09-01"),
        date_played: new Date("2022-09-05"),
        comment: "Good now but lost interest.",
        cover_url: cover(1091500),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Minecraft",
        genre: "survival",
        platform: "PC",
        status: "paused",
        favorite: false,
        hours_played: 200,
        rating: 4.5,
        price: "26.95",
        date_purchased: new Date("2019-01-01"),
        date_played: new Date("2019-01-05"),
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Assassin's Creed Valhalla",
        genre: "action",
        platform: "xbox",
        status: "paused",
        favorite: false,
        hours_played: 30,
        rating: 3.2,
        price: "29.99",
        date_purchased: new Date("2022-01-14"),
        date_played: new Date("2022-01-20"),
        comment: "Too long, got fatigued.",
        cover_url: cover(2208920),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Cities: Skylines",
        genre: "simulation",
        platform: "PC",
        status: "paused",
        favorite: false,
        hours_played: 60,
        rating: 4.0,
        price: "29.99",
        date_purchased: new Date("2020-11-01"),
        date_played: new Date("2020-11-05"),
        comment: null,
        cover_url: cover(255710),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Dropped ---
    {
        user_id: userId,
        title: "Starfield",
        genre: "role-playing",
        platform: "xbox",
        status: "dropped",
        favorite: false,
        hours_played: 10,
        rating: 2.5,
        price: "69.99",
        date_purchased: new Date("2023-09-06"),
        date_played: new Date("2023-09-07"),
        comment: "Not for me.",
        cover_url: cover(1716740),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Forspoken",
        genre: "action",
        platform: "playstation",
        status: "dropped",
        favorite: false,
        hours_played: 4,
        rating: 1.5,
        price: "69.99",
        date_purchased: new Date("2023-02-01"),
        date_played: new Date("2023-02-02"),
        comment: "Dialogue was unbearable.",
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Outriders",
        genre: "shooter",
        platform: "PC",
        status: "dropped",
        favorite: false,
        hours_played: 6,
        rating: 2.0,
        price: "0.00",
        date_purchased: new Date("2021-04-12"),
        date_played: new Date("2021-04-12"),
        comment: "Got boring fast.",
        cover_url: cover(680420),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Recent Purchases (last 12 months) ---
    {
        user_id: userId,
        title: "Split Fiction",
        genre: "action",
        platform: "PC",
        status: "playing",
        favorite: false,
        hours_played: 8,
        rating: 4.8,
        price: "39.99",
        date_purchased: new Date("2026-05-03"),
        date_played: new Date("2026-05-04"),
        comment: "Co-op is incredible.",
        cover_url: cover(2717700),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Balatro",
        genre: "puzzle",
        platform: "PC",
        status: "playing",
        favorite: true,
        hours_played: 22,
        rating: 4.9,
        price: "14.99",
        date_purchased: new Date("2026-04-22"),
        date_played: new Date("2026-04-22"),
        comment: "Impossibly addictive.",
        cover_url: cover(2379780),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Monster Hunter Wilds",
        genre: "action",
        platform: "PC",
        status: "playing",
        favorite: false,
        hours_played: 40,
        rating: 4.6,
        price: "69.99",
        date_purchased: new Date("2026-03-10"),
        date_played: new Date("2026-03-11"),
        comment: null,
        cover_url: cover(2246340),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Like a Dragon: Pirate Yakuza in Hawaii",
        genre: "action",
        platform: "PC",
        status: "completed",
        favorite: false,
        hours_played: 35,
        rating: 4.4,
        price: "59.99",
        date_purchased: new Date("2026-02-21"),
        date_played: new Date("2026-02-22"),
        comment: "Ridiculous in the best way.",
        cover_url: cover(2562020),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Indiana Jones and the Great Circle",
        genre: "action",
        platform: "xbox",
        status: "completed",
        favorite: false,
        hours_played: 20,
        rating: 4.5,
        price: "69.99",
        date_purchased: new Date("2025-12-09"),
        date_played: new Date("2025-12-10"),
        comment: "Nailed the Indiana Jones feel.",
        cover_url: cover(2677660),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Black Myth: Wukong",
        genre: "action",
        platform: "PC",
        status: "completed",
        favorite: true,
        hours_played: 45,
        rating: 4.7,
        price: "59.99",
        date_purchased: new Date("2025-11-20"),
        date_played: new Date("2025-11-21"),
        comment: "Stunning visuals, brutal combat.",
        cover_url: cover(2358720),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Metaphor: ReFantazio",
        genre: "role-playing",
        platform: "PC",
        status: "completed",
        favorite: true,
        hours_played: 80,
        rating: 4.9,
        price: "59.99",
        date_purchased: new Date("2025-10-11"),
        date_played: new Date("2025-10-12"),
        comment: "Atlus at their best.",
        cover_url: cover(1689550),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Astro Bot",
        genre: "platform",
        platform: "playstation",
        status: "completed",
        favorite: true,
        hours_played: 12,
        rating: 5.0,
        price: "59.99",
        date_purchased: new Date("2025-07-15"),
        date_played: new Date("2025-07-16"),
        comment: "Pure joy from start to finish.",
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Silent Hill 2",
        genre: "action",
        platform: "playstation",
        status: "completed",
        favorite: false,
        hours_played: 16,
        rating: 4.6,
        price: "59.99",
        date_purchased: new Date("2025-06-05"),
        date_played: new Date("2025-06-06"),
        comment: "Remake exceeded all expectations.",
        cover_url: cover(2124490),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Wishlist ---
    {
        user_id: userId,
        title: "Silksong",
        genre: "platform",
        platform: "nintendo",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: "When it comes out...",
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "GTA VI",
        genre: "action",
        platform: "playstation",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Fable",
        genre: "role-playing",
        platform: "xbox",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: "Hoping the reboot is good.",
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Metroid Prime 4",
        genre: "shooter",
        platform: "nintendo",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Avowed",
        genre: "role-playing",
        platform: "xbox",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
];

const seedDemo = async () => {
    await mongoClientPromise;
    console.log("Connected to MongoDB");

    const existing = await UserModel.findOne({ email: DEMO_EMAIL });

    if (existing) {
        await Promise.all([
            AuthModel.deleteMany({ user_id: String(existing._id) }),
            UserLibraryModel.deleteMany({ user_id: String(existing._id) }),
        ]);
        await UserModel.deleteOne({ _id: existing._id });
        console.log("Removed existing demo user");
    }

    const user = await UserModel.create({
        first_name: "Demo",
        last_name: "User",
        email: DEMO_EMAIL,
        email_verified: true,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    });

    const hash = await bcrypt.hash(DEMO_PASSWORD, 12);
    await AuthModel.create({ user_id: String(user._id), hash });

    await UserLibraryModel.insertMany(libraryGames(String(user._id)));

    console.log(`\nDemo seed complete`);
    console.log(`  Email:    ${DEMO_EMAIL}`);
    console.log(`  Password: ${DEMO_PASSWORD}`);
    console.log(`  Games:    ${libraryGames("").length} entries\n`);

    await mongoDisconnect();
};

seedDemo().catch((err) => {
    console.error("Demo seed failed:", err);
    process.exit(1);
});
