export const CDN = "https://cdn.cloudflare.steamstatic.com/steam/apps";
export const cover = (id: number) => `${CDN}/${id}/header.jpg`;

export const libraryGames = (userId: string) => [
    // --- Completed ---
    {
        user_id: userId,
        title: "Elden Ring",
        genre: "role-playing",
        platform: "PlayStation 5",
        status: "completed",
        favorite: true,
        hours_played: 120,
        rating: 4.9,
        price: "59.99",
        date_purchased: new Date("2022-02-25"),
        date_played: new Date("2022-03-01"),
        comment: "Masterpiece, best FromSoftware game.",
        cover_url: cover(1245620),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Hollow Knight",
        genre: "platformer",
        platform: "PC",
        status: "completed",
        favorite: true,
        hours_played: 42,
        rating: 4.8,
        price: "14.99",
        date_purchased: new Date("2021-06-10"),
        date_played: new Date("2021-06-15"),
        comment: null,
        cover_url: cover(367520),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Hades",
        genre: "action",
        platform: "Nintendo Switch",
        status: "completed",
        favorite: true,
        hours_played: 80,
        rating: 4.7,
        price: "24.99",
        date_purchased: new Date("2021-09-17"),
        date_played: new Date("2021-09-20"),
        comment: null,
        cover_url: cover(1145360),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Stardew Valley",
        genre: "simulation",
        platform: "PC",
        status: "completed",
        favorite: true,
        hours_played: 90,
        rating: 4.8,
        price: "0.00",
        date_purchased: new Date("2020-05-10"),
        date_played: new Date("2020-05-12"),
        comment: "Incredibly relaxing.",
        cover_url: cover(413150),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "God of War",
        genre: "action",
        platform: "PlayStation 5",
        status: "completed",
        favorite: true,
        hours_played: 35,
        rating: 4.9,
        price: "49.99",
        date_purchased: new Date("2020-08-12"),
        date_played: new Date("2020-08-14"),
        comment: "One of the best stories in gaming.",
        cover_url: cover(1593500),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "The Last of Us Part I",
        genre: "action",
        platform: "PlayStation 5",
        status: "completed",
        favorite: true,
        hours_played: 15,
        rating: 5.0,
        price: "39.99",
        date_purchased: new Date("2022-09-02"),
        date_played: new Date("2022-09-03"),
        comment: "Perfect game.",
        cover_url: cover(1888930),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Portal 2",
        genre: "puzzle",
        platform: "PC",
        status: "completed",
        favorite: false,
        hours_played: 10,
        rating: 4.9,
        price: "9.99",
        date_purchased: new Date("2018-11-23"),
        date_played: new Date("2018-12-01"),
        comment: "Brilliantly designed.",
        cover_url: cover(620),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Red Dead Redemption 2",
        genre: "action",
        platform: "PlayStation 5",
        status: "completed",
        favorite: true,
        hours_played: 110,
        rating: 4.9,
        price: "39.99",
        date_purchased: new Date("2019-03-15"),
        date_played: new Date("2019-03-20"),
        comment: "Unmatched world building and story.",
        cover_url: cover(1174180),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Celeste",
        genre: "platformer",
        platform: "Nintendo Switch",
        status: "completed",
        favorite: false,
        hours_played: 14,
        rating: 4.7,
        price: "19.99",
        date_purchased: new Date("2021-01-05"),
        date_played: new Date("2021-01-10"),
        comment: "Tight controls, great story.",
        cover_url: cover(504230),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Disco Elysium",
        genre: "role-playing",
        platform: "PC",
        status: "completed",
        favorite: false,
        hours_played: 40,
        rating: 4.6,
        price: "39.99",
        date_purchased: new Date("2021-04-01"),
        date_played: new Date("2021-04-05"),
        comment: "Most unique RPG I've played.",
        cover_url: cover(632470),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Playing ---
    {
        user_id: userId,
        title: "Baldur's Gate 3",
        genre: "role-playing",
        platform: "PC",
        status: "playing",
        favorite: false,
        hours_played: 35,
        rating: null,
        price: "59.99",
        date_purchased: new Date("2023-08-03"),
        date_played: new Date("2023-08-05"),
        comment: "Still going, incredible depth.",
        cover_url: cover(1086940),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "FIFA 25",
        genre: "sports",
        platform: "PlayStation 5",
        status: "playing",
        favorite: false,
        hours_played: 55,
        rating: 3.0,
        price: "69.99",
        date_purchased: new Date("2024-09-27"),
        date_played: new Date("2024-09-27"),
        comment: null,
        cover_url: cover(2669320),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Hades II",
        genre: "action",
        platform: "PC",
        status: "playing",
        favorite: false,
        hours_played: 12,
        rating: null,
        price: "24.99",
        date_purchased: new Date("2024-05-06"),
        date_played: new Date("2024-05-07"),
        comment: "Early access but already incredible.",
        cover_url: cover(1145350),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Mario Kart 8 Deluxe",
        genre: "racing",
        platform: "Nintendo Switch",
        status: "playing",
        favorite: false,
        hours_played: 28,
        rating: 4.3,
        price: "59.99",
        date_purchased: new Date("2023-12-25"),
        date_played: new Date("2023-12-25"),
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Forza Horizon 5",
        genre: "racing",
        platform: "Xbox One",
        status: "playing",
        favorite: false,
        hours_played: 22,
        rating: null,
        price: "59.99",
        date_purchased: new Date("2024-01-10"),
        date_played: new Date("2024-01-12"),
        comment: null,
        cover_url: cover(1551360),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Paused ---
    {
        user_id: userId,
        title: "Cyberpunk 2077",
        genre: "action",
        platform: "PC",
        status: "paused",
        favorite: false,
        hours_played: 18,
        rating: 3.5,
        price: "39.99",
        date_purchased: new Date("2022-09-01"),
        date_played: new Date("2022-09-05"),
        comment: "Good now but lost interest.",
        cover_url: cover(1091500),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Minecraft",
        genre: "other",
        platform: "PC",
        status: "paused",
        favorite: false,
        hours_played: 200,
        rating: 4.5,
        price: "26.95",
        date_purchased: new Date("2019-01-01"),
        date_played: new Date("2019-01-05"),
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Assassin's Creed Valhalla",
        genre: "action",
        platform: "Xbox One",
        status: "paused",
        favorite: false,
        hours_played: 30,
        rating: 3.2,
        price: "29.99",
        date_purchased: new Date("2022-01-14"),
        date_played: new Date("2022-01-20"),
        comment: "Too long, got fatigued.",
        cover_url: cover(2208920),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Cities: Skylines",
        genre: "simulation",
        platform: "PC",
        status: "paused",
        favorite: false,
        hours_played: 60,
        rating: 4.0,
        price: "29.99",
        date_purchased: new Date("2020-11-01"),
        date_played: new Date("2020-11-05"),
        comment: null,
        cover_url: cover(255710),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Dropped ---
    {
        user_id: userId,
        title: "Starfield",
        genre: "role-playing",
        platform: "Xbox One",
        status: "dropped",
        favorite: false,
        hours_played: 10,
        rating: 2.5,
        price: "69.99",
        date_purchased: new Date("2023-09-06"),
        date_played: new Date("2023-09-07"),
        comment: "Not for me.",
        cover_url: cover(1716740),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Forspoken",
        genre: "action",
        platform: "PlayStation 5",
        status: "dropped",
        favorite: false,
        hours_played: 4,
        rating: 1.5,
        price: "69.99",
        date_purchased: new Date("2023-02-01"),
        date_played: new Date("2023-02-02"),
        comment: "Dialogue was unbearable.",
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Outriders",
        genre: "shooter",
        platform: "PC",
        status: "dropped",
        favorite: false,
        hours_played: 6,
        rating: 2.0,
        price: "0.00",
        date_purchased: new Date("2021-04-12"),
        date_played: new Date("2021-04-12"),
        comment: "Got boring fast.",
        cover_url: cover(680420),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Recent Purchases (last 12 months) ---
    {
        user_id: userId,
        title: "Split Fiction",
        genre: "action",
        platform: "PC",
        status: "playing",
        favorite: false,
        hours_played: 8,
        rating: 4.8,
        price: "39.99",
        date_purchased: new Date("2026-05-03"),
        date_played: new Date("2026-05-04"),
        comment: "Co-op is incredible.",
        cover_url: cover(2717700),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Balatro",
        genre: "puzzle",
        platform: "PC",
        status: "playing",
        favorite: true,
        hours_played: 22,
        rating: 4.9,
        price: "14.99",
        date_purchased: new Date("2026-04-22"),
        date_played: new Date("2026-04-22"),
        comment: "Impossibly addictive.",
        cover_url: cover(2379780),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Monster Hunter Wilds",
        genre: "action",
        platform: "PC",
        status: "playing",
        favorite: false,
        hours_played: 40,
        rating: 4.6,
        price: "69.99",
        date_purchased: new Date("2026-03-10"),
        date_played: new Date("2026-03-11"),
        comment: null,
        cover_url: cover(2246340),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Like a Dragon: Pirate Yakuza in Hawaii",
        genre: "action",
        platform: "PC",
        status: "completed",
        favorite: false,
        hours_played: 35,
        rating: 4.4,
        price: "59.99",
        date_purchased: new Date("2026-02-21"),
        date_played: new Date("2026-02-22"),
        comment: "Ridiculous in the best way.",
        cover_url: cover(2562020),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Indiana Jones and the Great Circle",
        genre: "action",
        platform: "Xbox One",
        status: "completed",
        favorite: false,
        hours_played: 20,
        rating: 4.5,
        price: "69.99",
        date_purchased: new Date("2025-12-09"),
        date_played: new Date("2025-12-10"),
        comment: "Nailed the Indiana Jones feel.",
        cover_url: cover(2677660),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Black Myth: Wukong",
        genre: "action",
        platform: "PC",
        status: "completed",
        favorite: true,
        hours_played: 45,
        rating: 4.7,
        price: "59.99",
        date_purchased: new Date("2025-11-20"),
        date_played: new Date("2025-11-21"),
        comment: "Stunning visuals, brutal combat.",
        cover_url: cover(2358720),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Metaphor: ReFantazio",
        genre: "role-playing",
        platform: "PC",
        status: "completed",
        favorite: true,
        hours_played: 80,
        rating: 4.9,
        price: "59.99",
        date_purchased: new Date("2025-10-11"),
        date_played: new Date("2025-10-12"),
        comment: "Atlus at their best.",
        cover_url: cover(1689550),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Astro Bot",
        genre: "platformer",
        platform: "PlayStation 5",
        status: "completed",
        favorite: true,
        hours_played: 12,
        rating: 5.0,
        price: "59.99",
        date_purchased: new Date("2025-07-15"),
        date_played: new Date("2025-07-16"),
        comment: "Pure joy from start to finish.",
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Silent Hill 2",
        genre: "action",
        platform: "PlayStation 5",
        status: "completed",
        favorite: false,
        hours_played: 16,
        rating: 4.6,
        price: "59.99",
        date_purchased: new Date("2025-06-05"),
        date_played: new Date("2025-06-06"),
        comment: "Remake exceeded all expectations.",
        cover_url: cover(2124490),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Wishlist ---
    {
        user_id: userId,
        title: "Silksong",
        genre: "platformer",
        platform: "Nintendo Switch",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: "When it comes out...",
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "GTA VI",
        genre: "action",
        platform: "PlayStation 5",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Fable",
        genre: "role-playing",
        platform: "Xbox One",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: "Hoping the reboot is good.",
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Metroid Prime 4",
        genre: "shooter",
        platform: "Nintendo Switch",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Avowed",
        genre: "role-playing",
        platform: "Xbox One",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
];

export const FAKE_OWNERS = {
    alice: "aaaaaaaaaaaaaaaaaaaaaaaa",
    bob: "bbbbbbbbbbbbbbbbbbbbbbbb",
    carol: "cccccccccccccccccccccccc",
    dave: "dddddddddddddddddddddddd",
    eve: "eeeeeeeeeeeeeeeeeeeeeeee",
    frank: "ffffffffffffffffffffffff",
    grace: "111111111111111111111111",
    henry: "222222222222222222222222",
    iris: "333333333333333333333333",
    jack: "444444444444444444444444",
    kate: "555555555555555555555555",
    liam: "666666666666666666666666",
    mia: "777777777777777777777777",
    noah: "888888888888888888888888",
    olivia: "999999999999999999999999",
};

export const clubPosts = (userId: string, clubIdMap: Record<string, string>) => {
    const o = FAKE_OWNERS;
    const p = (
        clubName: string,
        author: string,
        content: string,
        is_spoiler: boolean,
        date: string,
    ) => ({
        club_id: clubIdMap[clubName],
        author,
        content,
        is_spoiler,
        created_at: new Date(date),
        updated_at: null,
        deleted_at: null,
    });

    return [
        // ── Souls Collective (20) — Elden Ring ────────────────────────────
        p("Souls Collective", userId, "Week 3 check-in — just cleared the Academy of Raya Lucaria. That Rennala fight was stunning, easily one of the most beautiful boss arenas in the game. Who else has made it to Liurnia?", false, "2026-06-17T18:30:00"),
        p("Souls Collective", o.alice, "Finally got past Margit on my 12th try. The window for dodging his hammer combo is so tight. Any tips for Godrick? I keep getting caught by the phase 2 dragon arm slam.", false, "2026-06-16T21:10:00"),
        p("Souls Collective", o.bob, "Waterfowl Dance is genuinely one of the most unfair attacks ever put in a video game. 30 attempts on Malenia and counting. I've watched the dodge tutorial so many times I can hear it in my sleep.", false, "2026-06-15T15:45:00"),
        p("Souls Collective", userId, "Just finished the Ranni questline. No spoilers but the ending hit completely different from what I expected. If you haven't started it, first step is finding Ranni's Rise in Liurnia.", true, "2026-06-14T23:00:00"),
        p("Souls Collective", o.grace, "Quick progression check — I'm still in Limgrave working through Stormveil and the rest of you sound like you're in completely different regions. Should I rush the main path or explore everything first?", false, "2026-06-13T12:20:00"),
        p("Souls Collective", o.iris, "I spent three hours reading item descriptions instead of playing. The lore in Elden Ring is ridiculous — every random piece of armour has a tragic backstory. George R.R. Martin really said let me cook.", false, "2026-06-12T20:00:00"),
        p("Souls Collective", o.bob, "Hot take: the Volcano Manor questline is the best questline in the game. The NPC reveals are genuinely shocking.", false, "2026-06-11T17:00:00"),
        p("Souls Collective", userId, "Lore deep dive — the connection between the Elden Ring, the Erdtree, and Marika is one of the most complex worldbuilding things I've seen in a game. I've been on the wiki for two hours.", false, "2026-06-11T14:30:00"),
        p("Souls Collective", o.alice, "Liurnia of the Lakes is insane in terms of scale. I thought Limgrave was big. I was so wrong.", false, "2026-06-10T19:45:00"),
        p("Souls Collective", o.grace, "Anyone else find the Glintstone Dragon completely optional and also impossible? Tried twice and left.", false, "2026-06-09T22:00:00"),
        p("Souls Collective", o.iris, "The Caelid swamp hit me harder than any boss. First time I saw a Grafted Scion wandering around I just stared at my screen for a minute.", false, "2026-06-08T16:10:00"),
        p("Souls Collective", userId, "Boss tier list: S — Morgott, Malenia, Radahn. A — Margit, Maliketh. B — Rennala. C — every Tree Sentinel. D — the two gargoyles fight.", false, "2026-06-07T21:30:00"),
        p("Souls Collective", o.alice, "Spirit summons are actually great once you start upgrading them. The Mimic Tear carried me through the Lakes of Rot. No shame.", false, "2026-06-06T18:00:00"),
        p("Souls Collective", o.bob, "I finally beat Malenia. That's it. That's the post.", false, "2026-06-05T23:45:00"),
        p("Souls Collective", o.grace, "Week 6 and I just discovered I've been playing the entire game without knowing you can parry. My whole build is wrong.", false, "2026-06-04T20:15:00"),
        p("Souls Collective", o.iris, "The Siofra River is the most beautiful area in the game. I went down there by accident and forgot to leave for two hours.", false, "2026-06-03T17:00:00"),
        p("Souls Collective", userId, "Found a way into the Shaded Castle through a back entrance that skips the whole approach. This game always has something new.", false, "2026-06-02T19:30:00"),
        p("Souls Collective", o.alice, "Playing with no fast travel to experience the world at walking pace. Probably a mistake but I've discovered so many things I would have missed.", false, "2026-06-01T15:00:00"),
        p("Souls Collective", o.bob, "Anyone have a good build recommendation? I've been levelling everything equally like an absolute beginner and I think I need to commit to something.", false, "2026-05-31T21:00:00"),
        p("Souls Collective", userId, "Hour count check — I'm at 67 hours and I feel like I've barely touched the surface. This game is enormous.", false, "2026-05-30T18:00:00"),

        // ── RPG Fellowship (10) — Baldur's Gate 3 ────────────────────────
        p("RPG Fellowship", o.alice, "Act 2 discussion thread — the atmosphere in the Shadow-Cursed Lands is incredible. The vibe shift from Act 1 is significant. We're discussing Moonrise Towers this Sunday.", false, "2026-06-16T10:00:00"),
        p("RPG Fellowship", userId, "Just got to Moonrise Towers. Without spoilers, the reveal there genuinely surprised me. Also I accidentally started a fight I wasn't ready for.", false, "2026-06-14T17:30:00"),
        p("RPG Fellowship", o.bob, "The companion reactivity in this game is on another level. Astarion called me out on something I did in the Underdark that I thought no one noticed. The writing is exceptional.", false, "2026-06-13T19:15:00"),
        p("RPG Fellowship", o.carol, "I misread a dialogue option and now half the camp hates me. I accidentally picked a fight with the Tieflings when I was trying to help them. Classic.", false, "2026-06-12T14:50:00"),
        p("RPG Fellowship", userId, "Spent four hours in the Underdark last night. Found the Arcane Tower and a bunch of things I'm still not sure what to do with. This place is massive.", false, "2026-06-11T22:00:00"),
        p("RPG Fellowship", o.alice, "Important PSA: save before the Goblin Camp, the Refugee outcome, and basically every conversation with Raphael. Learn from my mistakes.", false, "2026-06-10T16:30:00"),
        p("RPG Fellowship", o.bob, "Gale's character arc is hitting harder than expected. I went in planning to ignore him and now he's my favourite companion.", false, "2026-06-09T20:45:00"),
        p("RPG Fellowship", o.carol, "Quick poll — custom character or Dark Urge origin? I went custom first but I'm very curious about the Dark Urge route for my second playthrough.", false, "2026-06-08T11:00:00"),
        p("RPG Fellowship", userId, "The environmental storytelling is something else. Found a fully written scene in a small building with no quest marker, no prompt. Just there for anyone who looks.", false, "2026-06-07T19:00:00"),
        p("RPG Fellowship", o.alice, "Act 2 wrap-up — the pacing is tighter than Act 1 and the emotional payoffs are bigger. Looking forward to discussing Act 3 once everyone catches up.", false, "2026-06-06T21:00:00"),

        // ── Action RPG Alliance (10) — Monster Hunter Wilds ──────────────
        p("Action RPG Alliance", o.alice, "First session report — the new wounding mechanic changes the entire loop. Hunting feels more dynamic than any previous entry.", false, "2026-06-17T09:00:00"),
        p("Action RPG Alliance", o.bob, "The Doshaguma herd hunt is spectacular. Capcom really delivered on the scale promise this time.", false, "2026-06-15T20:30:00"),
        p("Action RPG Alliance", o.carol, "Good news for everyone who struggled with Rise: the guard timing in Wilds is much more forgiving. Lance main reporting in — this game respects us.", false, "2026-06-14T18:00:00"),
        p("Action RPG Alliance", o.dave, "Finished the story. The final boss is a spectacle. Won't say more.", true, "2026-06-12T23:30:00"),
        p("Action RPG Alliance", o.eve, "Anyone else using the wound → slinger burst → mount combo? It deletes parts incredibly fast. Spent an hour in the training area figuring this out.", false, "2026-06-11T15:00:00"),
        p("Action RPG Alliance", o.frank, "The new camp system is a massive quality of life improvement. Mid-hunt loadout swapping changes how you approach every quest.", false, "2026-06-10T17:45:00"),
        p("Action RPG Alliance", o.grace, "PS5 performance mode still has frame dips during the biggest battles. Not game-breaking but noticeable once you've seen it.", false, "2026-06-09T12:00:00"),
        p("Action RPG Alliance", o.henry, "Just hit HR 50. The tempered investigation pool is deep. We are in the real endgame now.", false, "2026-06-08T21:00:00"),
        p("Action RPG Alliance", o.alice, "Reminder that we're doing a group hunt this Saturday at 8pm. Bring your best loadout — we're targeting High Rank Rathian variants.", false, "2026-06-07T10:00:00"),
        p("Action RPG Alliance", o.bob, "Weapon tier list after 60 hours — S: Insect Glaive, Longsword, Switchaxe. A: Greatsword, Bow. Everything else is fine but these carry in the endgame.", false, "2026-06-06T19:30:00"),

        // ── The Completionists (5) — Elden Ring ───────────────────────────
        p("The Completionists", o.bob, "For 100% we need all endings. That means completing the Ranni, Fia, Goldmask, and Dung Eater questlines. I'm putting together a checklist for the club.", false, "2026-06-15T14:00:00"),
        p("The Completionists", o.alice, "All achievements acquired on PS5. 100% took 210 hours across two playthroughs. Every second was worth it.", false, "2026-06-13T20:00:00"),
        p("The Completionists", userId, "The Volcano Manor missable achievement caught me completely off guard. Check a guide before you approach the endgame — you can lock yourself out.", false, "2026-06-11T16:30:00"),
        p("The Completionists", o.dave, "Does multiplayer count toward progression? I've been helping people with Malenia for a week and I've learned her moveset better than my own character's.", false, "2026-06-09T19:00:00"),
        p("The Completionists", o.eve, "Progress update: I have every achievement except the final ending. After 180 hours I'm almost there.", false, "2026-06-07T22:00:00"),

        // ── Horror Hunters (5) — Silent Hill 2 ───────────────────────────
        p("Horror Hunters", o.carol, "Bloober Team genuinely knocked this out of the park. The Otherworld sections are more unsettling than the original in the best way.", false, "2026-06-16T21:00:00"),
        p("Horror Hunters", o.alice, "The combat changes take getting used to but the over-the-shoulder camera makes the dungeons so much more intense than I remembered.", false, "2026-06-14T19:30:00"),
        p("Horror Hunters", o.dave, "I did not expect the mannequin enemies to affect me this much. Had to take a break after the hospital section.", false, "2026-06-12T23:00:00"),
        p("Horror Hunters", o.eve, "The fog is doing tremendous work. It's so thick in the town sections that I genuinely didn't know what was behind me at any point.", false, "2026-06-10T20:00:00"),
        p("Horror Hunters", o.frank, "Going in without playing the original — should I watch a summary first or experience this version fresh? Don't want to miss references.", false, "2026-06-08T15:30:00"),

        // ── Couch Co-op Crew (5) — Split Fiction ──────────────────────────
        p("Couch Co-op Crew", o.bob, "Split Fiction topped It Takes Two for me. The variety of mechanics they packed into this is absurd — every chapter feels completely different.", false, "2026-06-17T11:00:00"),
        p("Couch Co-op Crew", o.carol, "The story hit way harder than I expected from a co-op platformer. The ending had me. No spoilers but prepare yourselves.", false, "2026-06-15T16:00:00"),
        p("Couch Co-op Crew", o.dave, "The sci-fi chapters vs the fantasy chapters debate is getting serious in our group. Both are incredible but for completely different reasons.", false, "2026-06-13T20:30:00"),
        p("Couch Co-op Crew", o.bob, "Looking for a co-op partner — my usual one is out of town and I want to keep going. Anyone free this weekend?", false, "2026-06-11T14:00:00"),
        p("Couch Co-op Crew", o.carol, "Finished it in two sessions over the weekend. Start to finish felt polished — no filler levels at all.", false, "2026-06-09T22:30:00"),

        // ── Open World Addicts (5) — Cyberpunk 2077 ──────────────────────
        p("Open World Addicts", o.carol, "2.0 plus Phantom Liberty transformed this game. If you tried it at launch and bounced, come back. It's a completely different experience now.", false, "2026-06-16T18:00:00"),
        p("Open World Addicts", o.alice, "The NCPD scanner jobs that turn into full side stories are incredible. Phantom Liberty has some of the best quests in any open world game I've played.", false, "2026-06-14T21:00:00"),
        p("Open World Addicts", o.bob, "V's story hits differently now that the game is finished and patched. The original ending has more weight when you actually experience it properly.", false, "2026-06-12T17:30:00"),
        p("Open World Addicts", o.dave, "Anyone else just driving around Night City with the radio on? The world building through just existing in the city is something special.", false, "2026-06-10T20:00:00"),
        p("Open World Addicts", o.eve, "Netrunner build in 2.0 is completely broken in the best way. Entire buildings cleared before I'm even spotted.", false, "2026-06-08T23:00:00"),

        // ── Roguelike Runners (3) — Hades II ─────────────────────────────
        p("Roguelike Runners", o.alice, "Melinoe's moveset is so much more versatile than Zagreus from the start. The omega attacks give the combat real depth and variety.", false, "2026-06-15T19:00:00"),
        p("Roguelike Runners", o.carol, "Finally cleared the surface route. The new boss is a genuine step up from the first game's final boss in difficulty.", true, "2026-06-13T22:00:00"),
        p("Roguelike Runners", o.dave, "32 heat run completed. Aphrodite Boons are secretly carrying a lot of builds — don't sleep on them.", false, "2026-06-11T20:30:00"),

        // ── Narrative First (3) — The Last of Us Part I ───────────────────
        p("Narrative First", o.bob, "The PS5 remake justifies its existence in the first three hours alone. The winter chapter in particular looks extraordinary.", false, "2026-06-14T20:00:00"),
        p("Narrative First", o.carol, "Playing this for the first time. Had the ending spoiled years ago and it still hit harder than I expected. The craft in the storytelling is something else.", false, "2026-06-12T18:30:00"),
        p("Narrative First", o.dave, "The way world building happens through environmental detail rather than exposition is a masterclass. The museum section is perfect game design.", false, "2026-06-10T21:00:00"),

        // ── Simulation Station (3) — Cities Skylines ─────────────────────
        p("Simulation Station", o.bob, "My city just hit 80k population and immediately collapsed due to traffic. Back to square one with better highway planning this time.", false, "2026-06-16T15:00:00"),
        p("Simulation Station", o.dave, "The new district policies change so much. Tourist economy is genuinely viable with the right zoning setup.", false, "2026-06-14T12:00:00"),
        p("Simulation Station", o.eve, "Anyone want to share city screenshots? I've been building a realistic coastal town and it's finally starting to look the way I imagined it.", false, "2026-06-12T19:00:00"),

        // ── Soulslike & Chill (3) — Lies of P ────────────────────────────
        p("Soulslike & Chill", o.alice, "Lies of P is the most polished soulslike outside of FromSoftware. The weapon assembly system alone makes it worth playing.", false, "2026-06-17T16:00:00"),
        p("Soulslike & Chill", o.carol, "The lie/truth mechanic affecting the ending is a clever twist on the formula. Already planning a second playthrough to see the other outcome.", true, "2026-06-15T21:00:00"),
        p("Soulslike & Chill", o.dave, "Boss tip for anyone stuck on the Eldest of the Black Rabbit Brotherhood — focus on staggering. Heavy weapons break his stance fast.", false, "2026-06-13T18:00:00"),

        // ── Racing League (1) ─────────────────────────────────────────────
        p("Racing League", o.alice, "Forza Horizon 5 weekly challenge is live — this week is S2 Class in the desert circuit. Post your lap times below, winner gets bragging rights.", false, "2026-06-16T09:00:00"),

        // ── The Long Game (1) ─────────────────────────────────────────────
        p("The Long Game: For Players with No Quit in Them", o.bob, "We are 25 hours into RDR2 and we haven't left the first snowy area yet. This is exactly what this club was created for.", false, "2026-06-14T22:00:00"),

        // ── Puzzle Enthusiasts (1) ────────────────────────────────────────
        p("Puzzle Enthusiasts", o.bob, "Portal 2 co-op is available for anyone who wants to run the bonus chambers together. The timing puzzles require actual coordination so come prepared.", false, "2026-06-13T17:00:00"),

        // ── Retro Revival (1) ─────────────────────────────────────────────
        p("Retro Revival", o.alice, "Nominating Shadow of the Colossus remaster for our next pick. The PS4 version has some quality of life improvements worth discussing alongside the original.", false, "2026-06-10T14:00:00"),

        // ── Strategy & Tactics (1) ────────────────────────────────────────
        p("Strategy & Tactics", o.carol, "Suggesting Crusader Kings III for our next pick. The depth is absurd and the emergent storytelling fits exactly what this club is about.", false, "2026-06-09T16:00:00"),

        // ── Indie Explorers (1) ───────────────────────────────────────────
        p("Indie Explorers", userId, "Club is officially open for game nominations. Drop your indie recommendations below and we'll vote on the first pick this weekend.", false, "2026-06-08T11:00:00"),

        // ── The Backlog (1) ───────────────────────────────────────────────
        p("The Backlog", o.carol, "Monthly accountability check — how many games has everyone crossed off the backlog this month? I finally finished Cyberpunk 2077. Only had it since 2021.", false, "2026-06-07T20:00:00"),

        // Nintendo Nights → 0 posts (empty state)
        // FPS Legends → 0 posts (empty state)
    ];
};

const mb = (uid: string, date: string) => ({ user_id: uid, joined_at: new Date(date) });

export const clubs = (userId: string) => [
    {
        name: "Souls Collective",
        owner: userId,
        avatar_url: null,
        description:
            "For those who love punishment. We play one FromSoftware game at a time, together.",
        members: [
            mb(userId, "2025-09-01"),
            mb(FAKE_OWNERS.alice, "2025-09-03"),
            mb(FAKE_OWNERS.bob, "2025-09-05"),
            mb(FAKE_OWNERS.grace, "2025-09-08"),
            mb(FAKE_OWNERS.iris, "2025-09-12"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Elden Ring",
            cover_url: cover(1245620),
            start_date: new Date("2026-05-01"),
            end_date: new Date("2026-06-30"),
        },
        past_games: [
            { title: "Dark Souls III", cover_url: cover(374320), end_date: new Date("2026-02-28") },
            { title: "Sekiro", cover_url: cover(814380), end_date: new Date("2025-11-30") },
        ],
        created_at: new Date("2025-09-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Indie Explorers",
        owner: userId,
        avatar_url: null,
        description: "We dig through the itch.io backlog so you don't have to.",
        members: [
            mb(userId, "2026-01-15"),
            mb(FAKE_OWNERS.dave, "2026-01-18"),
            mb(FAKE_OWNERS.henry, "2026-01-22"),
            mb(FAKE_OWNERS.kate, "2026-01-25"),
            mb(FAKE_OWNERS.liam, "2026-01-28"),
            mb(FAKE_OWNERS.bob, "2026-02-01"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: null,
        past_games: [],
        created_at: new Date("2026-01-15"),
        updated_at: null,
        deleted_at: null,
    },

    // --- Dev user is a member but does not own ---

    {
        name: "RPG Fellowship",
        owner: FAKE_OWNERS.alice,
        avatar_url: null,
        description:
            "Deep stories, rich worlds, long save files. We work through one RPG at a time as a group.",
        members: [
            mb(FAKE_OWNERS.alice, "2025-06-10"),
            mb(FAKE_OWNERS.bob, "2025-06-12"),
            mb(FAKE_OWNERS.carol, "2025-06-15"),
            mb(userId, "2025-06-20"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Baldur's Gate 3",
            cover_url: cover(1086940),
            start_date: new Date("2026-04-01"),
            end_date: new Date("2026-07-31"),
        },
        past_games: [
            { title: "Disco Elysium", cover_url: cover(632470), end_date: new Date("2026-01-31") },
            {
                title: "Metaphor: ReFantazio",
                cover_url: cover(1689550),
                end_date: new Date("2025-09-30"),
            },
        ],
        created_at: new Date("2025-06-10"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "The Completionists",
        owner: FAKE_OWNERS.bob,
        avatar_url: null,
        description: "100% or nothing. We don't move on until every achievement is unlocked.",
        members: [
            mb(FAKE_OWNERS.alice, "2025-03-20"),
            mb(FAKE_OWNERS.bob, "2025-03-20"),
            mb(FAKE_OWNERS.carol, "2025-03-24"),
            mb(userId, "2025-03-28"),
            mb(FAKE_OWNERS.dave, "2025-04-02"),
            mb(FAKE_OWNERS.eve, "2025-04-07"),
            mb(FAKE_OWNERS.frank, "2025-04-12"),
            mb(FAKE_OWNERS.grace, "2025-04-18"),
            mb(FAKE_OWNERS.henry, "2025-04-25"),
            mb(FAKE_OWNERS.iris, "2025-05-01"),
            mb(FAKE_OWNERS.jack, "2025-05-08"),
            mb(FAKE_OWNERS.kate, "2025-05-15"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Elden Ring",
            cover_url: cover(1245620),
            start_date: new Date("2026-03-01"),
            end_date: new Date("2026-06-30"),
        },
        past_games: [
            { title: "Hollow Knight", cover_url: cover(367520), end_date: new Date("2026-01-15") },
            { title: "Celeste", cover_url: cover(504230), end_date: new Date("2025-10-31") },
            { title: "Hades", cover_url: cover(1145360), end_date: new Date("2025-07-31") },
        ],
        created_at: new Date("2025-03-20"),
        updated_at: null,
        deleted_at: null,
    },

    // --- Dev user has NOT joined (Join button visible) ---

    {
        name: "Horror Hunters",
        owner: FAKE_OWNERS.carol,
        avatar_url: null,
        description: "We only play in the dark. One horror game per month, voted on by the group.",
        members: [
            mb(FAKE_OWNERS.alice, "2025-10-01"),
            mb(FAKE_OWNERS.carol, "2025-10-01"),
            mb(FAKE_OWNERS.dave, "2025-10-03"),
            mb(FAKE_OWNERS.eve, "2025-10-05"),
            mb(FAKE_OWNERS.frank, "2025-10-08"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Silent Hill 2",
            cover_url: cover(2124490),
            start_date: new Date("2026-05-15"),
            end_date: new Date("2026-06-15"),
        },
        past_games: [
            {
                title: "Resident Evil Village",
                cover_url: cover(1196590),
                end_date: new Date("2026-04-30"),
            },
        ],
        created_at: new Date("2025-10-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Racing League",
        owner: FAKE_OWNERS.alice,
        avatar_url: null,
        description:
            "Weekly time trials, weekend tournaments. Sim racers and arcade racers both welcome.",
        members: [
            mb(FAKE_OWNERS.alice, "2026-02-14"),
            mb(FAKE_OWNERS.bob, "2026-02-16"),
            mb(FAKE_OWNERS.dave, "2026-02-19"),
            mb(FAKE_OWNERS.eve, "2026-02-23"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Forza Horizon 5",
            cover_url: cover(1551360),
            start_date: new Date("2026-05-01"),
            end_date: null,
        },
        past_games: [],
        created_at: new Date("2026-02-14"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Couch Co-op Crew",
        owner: FAKE_OWNERS.bob,
        avatar_url: null,
        description:
            "Split-screen, local multiplayer, online co-op — if you can play it together, we're playing it.",
        members: [
            mb(FAKE_OWNERS.bob, "2025-11-05"),
            mb(FAKE_OWNERS.carol, "2025-11-07"),
            mb(FAKE_OWNERS.dave, "2025-11-10"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Split Fiction",
            cover_url: cover(2717700),
            start_date: new Date("2026-05-10"),
            end_date: new Date("2026-06-10"),
        },
        past_games: [
            { title: "Portal 2", cover_url: cover(620), end_date: new Date("2026-04-30") },
        ],
        created_at: new Date("2025-11-05"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Retro Revival",
        owner: FAKE_OWNERS.carol,
        avatar_url: null,
        description:
            "Going back to the classics. PS1, PS2, SNES, N64 — if it's older than 2005, it's on the list.",
        members: [
            mb(FAKE_OWNERS.alice, "2025-05-20"),
            mb(FAKE_OWNERS.carol, "2025-05-20"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: null,
        past_games: [
            {
                title: "Resident Evil 4 (Original)",
                cover_url: null,
                end_date: new Date("2026-03-31"),
            },
            { title: "Shadow of the Colossus", cover_url: null, end_date: new Date("2025-12-31") },
            { title: "Ico", cover_url: null, end_date: new Date("2025-09-30") },
        ],
        created_at: new Date("2025-05-20"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "FPS Legends",
        owner: FAKE_OWNERS.alice,
        avatar_url: null,
        description: "Private squad for our weekly FPS sessions. Invite only.",
        members: [
            mb(FAKE_OWNERS.alice, "2026-03-01"),
            mb(FAKE_OWNERS.bob, "2026-03-03"),
            mb(FAKE_OWNERS.dave, "2026-03-05"),
            mb(FAKE_OWNERS.eve, "2026-03-07"),
            mb(FAKE_OWNERS.frank, "2026-03-09"),
            mb(FAKE_OWNERS.grace, "2026-03-11"),
        ],
        visibility: "private",
        invite_code: "FPS-7X2K",
        current_game: {
            title: "Hades II",
            cover_url: cover(1145350),
            start_date: new Date("2026-06-01"),
            end_date: null,
        },
        past_games: [],
        created_at: new Date("2026-03-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "The Long Game: For Players with No Quit in Them",
        owner: FAKE_OWNERS.bob,
        avatar_url: null,
        description: "We exclusively play games with 80+ hour runtimes. No short games allowed.",
        members: [
            mb(FAKE_OWNERS.bob, "2025-12-01"),
            mb(FAKE_OWNERS.dave, "2025-12-04"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Red Dead Redemption 2",
            cover_url: cover(1174180),
            start_date: new Date("2026-04-15"),
            end_date: new Date("2026-08-31"),
        },
        past_games: [
            {
                title: "Baldur's Gate 3",
                cover_url: cover(1086940),
                end_date: new Date("2026-03-31"),
            },
        ],
        created_at: new Date("2025-12-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Open World Addicts",
        owner: FAKE_OWNERS.carol,
        avatar_url: null,
        description: "We lose ourselves in open worlds. The bigger the map the better.",
        members: [
            mb(FAKE_OWNERS.alice, "2025-04-15"),
            mb(FAKE_OWNERS.bob, "2025-04-17"),
            mb(FAKE_OWNERS.carol, "2025-04-20"),
            mb(FAKE_OWNERS.dave, "2025-04-23"),
            mb(FAKE_OWNERS.eve, "2025-04-27"),
            mb(FAKE_OWNERS.frank, "2025-05-01"),
            mb(FAKE_OWNERS.grace, "2025-05-05"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Cyberpunk 2077",
            cover_url: cover(1091500),
            start_date: new Date("2026-05-20"),
            end_date: null,
        },
        past_games: [
            {
                title: "Red Dead Redemption 2",
                cover_url: cover(1174180),
                end_date: new Date("2026-04-30"),
            },
            { title: "God of War", cover_url: cover(1593500), end_date: new Date("2025-12-31") },
        ],
        created_at: new Date("2025-04-15"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Roguelike Runners",
        owner: FAKE_OWNERS.alice,
        avatar_url: null,
        description:
            "Permanent death, procedural generation, one more run. Every week we share our best runs.",
        members: [
            mb(FAKE_OWNERS.alice, "2025-08-10"),
            mb(FAKE_OWNERS.carol, "2025-08-12"),
            mb(FAKE_OWNERS.dave, "2025-08-15"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Hades II",
            cover_url: cover(1145350),
            start_date: new Date("2026-05-06"),
            end_date: null,
        },
        past_games: [
            { title: "Hades", cover_url: cover(1145360), end_date: new Date("2026-02-28") },
            { title: "Balatro", cover_url: cover(2379780), end_date: new Date("2025-11-30") },
        ],
        created_at: new Date("2025-08-10"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Puzzle Enthusiasts",
        owner: FAKE_OWNERS.bob,
        avatar_url: null,
        description:
            "Brain-melting puzzles only. We discuss solutions, compare times, and suffer together.",
        members: [
            mb(FAKE_OWNERS.bob, "2026-04-01"),
            mb(FAKE_OWNERS.dave, "2026-04-03"),
            mb(FAKE_OWNERS.eve, "2026-04-06"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Portal 2",
            cover_url: cover(620),
            start_date: new Date("2026-05-25"),
            end_date: new Date("2026-06-25"),
        },
        past_games: [],
        created_at: new Date("2026-04-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Strategy & Tactics",
        owner: FAKE_OWNERS.carol,
        avatar_url: null,
        description: "Turn-based, real-time, 4X — if it requires a plan, we're interested.",
        members: [
            mb(FAKE_OWNERS.alice, "2025-07-04"),
            mb(FAKE_OWNERS.carol, "2025-07-04"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: null,
        past_games: [
            { title: "Civilization VI", cover_url: null, end_date: new Date("2026-04-15") },
            { title: "XCOM 2", cover_url: null, end_date: new Date("2025-12-15") },
        ],
        created_at: new Date("2025-07-04"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Action RPG Alliance",
        owner: FAKE_OWNERS.alice,
        avatar_url: null,
        description: "The sweet spot between action and RPG. Fast combat, deep builds, great loot.",
        members: [
            mb(FAKE_OWNERS.alice, "2024-11-01"),
            mb(FAKE_OWNERS.bob, "2024-11-03"),
            mb(FAKE_OWNERS.carol, "2024-11-05"),
            mb(FAKE_OWNERS.dave, "2024-11-08"),
            mb(FAKE_OWNERS.eve, "2024-11-12"),
            mb(FAKE_OWNERS.frank, "2024-11-16"),
            mb(FAKE_OWNERS.grace, "2024-11-21"),
            mb(FAKE_OWNERS.henry, "2024-11-27"),
            mb(FAKE_OWNERS.iris, "2024-12-03"),
            mb(FAKE_OWNERS.jack, "2024-12-10"),
            mb(FAKE_OWNERS.kate, "2024-12-17"),
            mb(FAKE_OWNERS.liam, "2024-12-25"),
            mb(FAKE_OWNERS.mia, "2025-01-02"),
            mb(FAKE_OWNERS.noah, "2025-01-10"),
            mb(FAKE_OWNERS.olivia, "2025-01-18"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Monster Hunter Wilds",
            cover_url: cover(2246340),
            start_date: new Date("2026-03-15"),
            end_date: null,
        },
        past_games: [
            { title: "Elden Ring", cover_url: cover(1245620), end_date: new Date("2026-02-28") },
            { title: "God of War", cover_url: cover(1593500), end_date: new Date("2025-10-31") },
            { title: "Sekiro", cover_url: cover(814380), end_date: new Date("2025-06-30") },
        ],
        created_at: new Date("2024-11-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Narrative First",
        owner: FAKE_OWNERS.bob,
        avatar_url: null,
        description:
            "Gameplay is secondary. We're here for the writing, the characters, and the moments that stick with you.",
        members: [
            mb(FAKE_OWNERS.bob, "2025-02-14"),
            mb(FAKE_OWNERS.carol, "2025-02-16"),
            mb(FAKE_OWNERS.dave, "2025-02-19"),
            mb(FAKE_OWNERS.eve, "2025-02-23"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "The Last of Us Part I",
            cover_url: cover(1888930),
            start_date: new Date("2026-05-01"),
            end_date: new Date("2026-06-30"),
        },
        past_games: [
            { title: "Disco Elysium", cover_url: cover(632470), end_date: new Date("2026-03-31") },
            {
                title: "Red Dead Redemption 2",
                cover_url: cover(1174180),
                end_date: new Date("2025-11-30"),
            },
        ],
        created_at: new Date("2025-02-14"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "The Backlog",
        owner: FAKE_OWNERS.carol,
        avatar_url: null,
        description:
            "Dedicated to finally finishing the games we bought and forgot about. No shame, only progress.",
        members: [
            mb(FAKE_OWNERS.alice, "2025-01-01"),
            mb(FAKE_OWNERS.bob, "2025-01-03"),
            mb(FAKE_OWNERS.carol, "2025-01-06"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: null,
        past_games: [
            {
                title: "Cyberpunk 2077",
                cover_url: cover(1091500),
                end_date: new Date("2026-05-31"),
            },
            { title: "Stardew Valley", cover_url: cover(413150), end_date: new Date("2026-02-28") },
            { title: "Hades", cover_url: cover(1145360), end_date: new Date("2025-10-31") },
            { title: "Celeste", cover_url: cover(504230), end_date: new Date("2025-07-31") },
        ],
        created_at: new Date("2025-01-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Nintendo Nights",
        owner: FAKE_OWNERS.alice,
        avatar_url: null,
        description:
            "Nintendo exclusives only. We play through the Switch library one game at a time.",
        members: [
            mb(FAKE_OWNERS.alice, "2026-05-01"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: null,
        past_games: [],
        created_at: new Date("2026-05-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Simulation Station",
        owner: FAKE_OWNERS.bob,
        avatar_url: null,
        description:
            "City builders, farming sims, life sims. If it simulates something, we're playing it.",
        members: [
            mb(FAKE_OWNERS.bob, "2025-09-15"),
            mb(FAKE_OWNERS.dave, "2025-09-17"),
            mb(FAKE_OWNERS.eve, "2025-09-20"),
            mb(FAKE_OWNERS.frank, "2025-09-24"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Cities: Skylines",
            cover_url: cover(255710),
            start_date: new Date("2026-04-20"),
            end_date: null,
        },
        past_games: [
            { title: "Stardew Valley", cover_url: cover(413150), end_date: new Date("2026-03-31") },
        ],
        created_at: new Date("2025-09-15"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Soulslike & Chill",
        owner: FAKE_OWNERS.carol,
        avatar_url: null,
        description:
            "We appreciate the genre but we don't gatekeep. All skill levels welcome, summons encouraged.",
        members: [
            mb(FAKE_OWNERS.alice, "2025-05-01"),
            mb(FAKE_OWNERS.carol, "2025-05-01"),
            mb(FAKE_OWNERS.dave, "2025-05-03"),
            mb(FAKE_OWNERS.eve, "2025-05-06"),
            mb(FAKE_OWNERS.frank, "2025-05-09"),
            mb(FAKE_OWNERS.grace, "2025-05-13"),
            mb(FAKE_OWNERS.henry, "2025-05-17"),
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Lies of P",
            cover_url: null,
            start_date: new Date("2026-05-15"),
            end_date: new Date("2026-07-15"),
        },
        past_games: [
            { title: "Sekiro", cover_url: cover(814380), end_date: new Date("2026-04-30") },
            { title: "Dark Souls III", cover_url: cover(374320), end_date: new Date("2025-12-31") },
            { title: "Elden Ring", cover_url: cover(1245620), end_date: new Date("2025-08-31") },
        ],
        created_at: new Date("2025-05-01"),
        updated_at: null,
        deleted_at: null,
    },
];
