export const CDN = "https://cdn.cloudflare.steamstatic.com/steam/apps";
export const cover = (id: number) => `${CDN}/${id}/header.jpg`;

export const libraryGames = (userId: string) => [
    // --- Completed ---
    {
        user_id: userId,
        title: "Elden Ring",
        genre: "role-playing",
        platform: "PlayStation 5",
        status: "completed",
        favorite: true,
        hours_played: 120,
        rating: 4.9,
        price: "59.99",
        date_purchased: new Date("2022-02-25"),
        date_played: new Date("2022-03-01"),
        comment: "Masterpiece, best FromSoftware game.",
        cover_url: cover(1245620),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Hollow Knight",
        genre: "platformer",
        platform: "PC",
        status: "completed",
        favorite: true,
        hours_played: 42,
        rating: 4.8,
        price: "14.99",
        date_purchased: new Date("2021-06-10"),
        date_played: new Date("2021-06-15"),
        comment: null,
        cover_url: cover(367520),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Hades",
        genre: "action",
        platform: "Nintendo Switch",
        status: "completed",
        favorite: true,
        hours_played: 80,
        rating: 4.7,
        price: "24.99",
        date_purchased: new Date("2021-09-17"),
        date_played: new Date("2021-09-20"),
        comment: null,
        cover_url: cover(1145360),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Stardew Valley",
        genre: "simulation",
        platform: "PC",
        status: "completed",
        favorite: true,
        hours_played: 90,
        rating: 4.8,
        price: "0.00",
        date_purchased: new Date("2020-05-10"),
        date_played: new Date("2020-05-12"),
        comment: "Incredibly relaxing.",
        cover_url: cover(413150),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "God of War",
        genre: "action",
        platform: "PlayStation 5",
        status: "completed",
        favorite: true,
        hours_played: 35,
        rating: 4.9,
        price: "49.99",
        date_purchased: new Date("2020-08-12"),
        date_played: new Date("2020-08-14"),
        comment: "One of the best stories in gaming.",
        cover_url: cover(1593500),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "The Last of Us Part I",
        genre: "action",
        platform: "PlayStation 5",
        status: "completed",
        favorite: true,
        hours_played: 15,
        rating: 5.0,
        price: "39.99",
        date_purchased: new Date("2022-09-02"),
        date_played: new Date("2022-09-03"),
        comment: "Perfect game.",
        cover_url: cover(1888930),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Portal 2",
        genre: "puzzle",
        platform: "PC",
        status: "completed",
        favorite: false,
        hours_played: 10,
        rating: 4.9,
        price: "9.99",
        date_purchased: new Date("2018-11-23"),
        date_played: new Date("2018-12-01"),
        comment: "Brilliantly designed.",
        cover_url: cover(620),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Red Dead Redemption 2",
        genre: "action",
        platform: "PlayStation 5",
        status: "completed",
        favorite: true,
        hours_played: 110,
        rating: 4.9,
        price: "39.99",
        date_purchased: new Date("2019-03-15"),
        date_played: new Date("2019-03-20"),
        comment: "Unmatched world building and story.",
        cover_url: cover(1174180),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Celeste",
        genre: "platformer",
        platform: "Nintendo Switch",
        status: "completed",
        favorite: false,
        hours_played: 14,
        rating: 4.7,
        price: "19.99",
        date_purchased: new Date("2021-01-05"),
        date_played: new Date("2021-01-10"),
        comment: "Tight controls, great story.",
        cover_url: cover(504230),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Disco Elysium",
        genre: "role-playing",
        platform: "PC",
        status: "completed",
        favorite: false,
        hours_played: 40,
        rating: 4.6,
        price: "39.99",
        date_purchased: new Date("2021-04-01"),
        date_played: new Date("2021-04-05"),
        comment: "Most unique RPG I've played.",
        cover_url: cover(632470),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Playing ---
    {
        user_id: userId,
        title: "Baldur's Gate 3",
        genre: "role-playing",
        platform: "PC",
        status: "playing",
        favorite: false,
        hours_played: 35,
        rating: null,
        price: "59.99",
        date_purchased: new Date("2023-08-03"),
        date_played: new Date("2023-08-05"),
        comment: "Still going, incredible depth.",
        cover_url: cover(1086940),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "FIFA 25",
        genre: "sports",
        platform: "PlayStation 5",
        status: "playing",
        favorite: false,
        hours_played: 55,
        rating: 3.0,
        price: "69.99",
        date_purchased: new Date("2024-09-27"),
        date_played: new Date("2024-09-27"),
        comment: null,
        cover_url: cover(2669320),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Hades II",
        genre: "action",
        platform: "PC",
        status: "playing",
        favorite: false,
        hours_played: 12,
        rating: null,
        price: "24.99",
        date_purchased: new Date("2024-05-06"),
        date_played: new Date("2024-05-07"),
        comment: "Early access but already incredible.",
        cover_url: cover(1145350),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Mario Kart 8 Deluxe",
        genre: "racing",
        platform: "Nintendo Switch",
        status: "playing",
        favorite: false,
        hours_played: 28,
        rating: 4.3,
        price: "59.99",
        date_purchased: new Date("2023-12-25"),
        date_played: new Date("2023-12-25"),
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Forza Horizon 5",
        genre: "racing",
        platform: "Xbox One",
        status: "playing",
        favorite: false,
        hours_played: 22,
        rating: null,
        price: "59.99",
        date_purchased: new Date("2024-01-10"),
        date_played: new Date("2024-01-12"),
        comment: null,
        cover_url: cover(1551360),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Paused ---
    {
        user_id: userId,
        title: "Cyberpunk 2077",
        genre: "action",
        platform: "PC",
        status: "paused",
        favorite: false,
        hours_played: 18,
        rating: 3.5,
        price: "39.99",
        date_purchased: new Date("2022-09-01"),
        date_played: new Date("2022-09-05"),
        comment: "Good now but lost interest.",
        cover_url: cover(1091500),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Minecraft",
        genre: "other",
        platform: "PC",
        status: "paused",
        favorite: false,
        hours_played: 200,
        rating: 4.5,
        price: "26.95",
        date_purchased: new Date("2019-01-01"),
        date_played: new Date("2019-01-05"),
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Assassin's Creed Valhalla",
        genre: "action",
        platform: "Xbox One",
        status: "paused",
        favorite: false,
        hours_played: 30,
        rating: 3.2,
        price: "29.99",
        date_purchased: new Date("2022-01-14"),
        date_played: new Date("2022-01-20"),
        comment: "Too long, got fatigued.",
        cover_url: cover(2208920),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Cities: Skylines",
        genre: "simulation",
        platform: "PC",
        status: "paused",
        favorite: false,
        hours_played: 60,
        rating: 4.0,
        price: "29.99",
        date_purchased: new Date("2020-11-01"),
        date_played: new Date("2020-11-05"),
        comment: null,
        cover_url: cover(255710),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Dropped ---
    {
        user_id: userId,
        title: "Starfield",
        genre: "role-playing",
        platform: "Xbox One",
        status: "dropped",
        favorite: false,
        hours_played: 10,
        rating: 2.5,
        price: "69.99",
        date_purchased: new Date("2023-09-06"),
        date_played: new Date("2023-09-07"),
        comment: "Not for me.",
        cover_url: cover(1716740),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Forspoken",
        genre: "action",
        platform: "PlayStation 5",
        status: "dropped",
        favorite: false,
        hours_played: 4,
        rating: 1.5,
        price: "69.99",
        date_purchased: new Date("2023-02-01"),
        date_played: new Date("2023-02-02"),
        comment: "Dialogue was unbearable.",
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Outriders",
        genre: "shooter",
        platform: "PC",
        status: "dropped",
        favorite: false,
        hours_played: 6,
        rating: 2.0,
        price: "0.00",
        date_purchased: new Date("2021-04-12"),
        date_played: new Date("2021-04-12"),
        comment: "Got boring fast.",
        cover_url: cover(680420),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Recent Purchases (last 12 months) ---
    {
        user_id: userId,
        title: "Split Fiction",
        genre: "action",
        platform: "PC",
        status: "playing",
        favorite: false,
        hours_played: 8,
        rating: 4.8,
        price: "39.99",
        date_purchased: new Date("2026-05-03"),
        date_played: new Date("2026-05-04"),
        comment: "Co-op is incredible.",
        cover_url: cover(2717700),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Balatro",
        genre: "puzzle",
        platform: "PC",
        status: "playing",
        favorite: true,
        hours_played: 22,
        rating: 4.9,
        price: "14.99",
        date_purchased: new Date("2026-04-22"),
        date_played: new Date("2026-04-22"),
        comment: "Impossibly addictive.",
        cover_url: cover(2379780),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Monster Hunter Wilds",
        genre: "action",
        platform: "PC",
        status: "playing",
        favorite: false,
        hours_played: 40,
        rating: 4.6,
        price: "69.99",
        date_purchased: new Date("2026-03-10"),
        date_played: new Date("2026-03-11"),
        comment: null,
        cover_url: cover(2246340),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Like a Dragon: Pirate Yakuza in Hawaii",
        genre: "action",
        platform: "PC",
        status: "completed",
        favorite: false,
        hours_played: 35,
        rating: 4.4,
        price: "59.99",
        date_purchased: new Date("2026-02-21"),
        date_played: new Date("2026-02-22"),
        comment: "Ridiculous in the best way.",
        cover_url: cover(2562020),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Indiana Jones and the Great Circle",
        genre: "action",
        platform: "Xbox One",
        status: "completed",
        favorite: false,
        hours_played: 20,
        rating: 4.5,
        price: "69.99",
        date_purchased: new Date("2025-12-09"),
        date_played: new Date("2025-12-10"),
        comment: "Nailed the Indiana Jones feel.",
        cover_url: cover(2677660),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Black Myth: Wukong",
        genre: "action",
        platform: "PC",
        status: "completed",
        favorite: true,
        hours_played: 45,
        rating: 4.7,
        price: "59.99",
        date_purchased: new Date("2025-11-20"),
        date_played: new Date("2025-11-21"),
        comment: "Stunning visuals, brutal combat.",
        cover_url: cover(2358720),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Metaphor: ReFantazio",
        genre: "role-playing",
        platform: "PC",
        status: "completed",
        favorite: true,
        hours_played: 80,
        rating: 4.9,
        price: "59.99",
        date_purchased: new Date("2025-10-11"),
        date_played: new Date("2025-10-12"),
        comment: "Atlus at their best.",
        cover_url: cover(1689550),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Astro Bot",
        genre: "platformer",
        platform: "PlayStation 5",
        status: "completed",
        favorite: true,
        hours_played: 12,
        rating: 5.0,
        price: "59.99",
        date_purchased: new Date("2025-07-15"),
        date_played: new Date("2025-07-16"),
        comment: "Pure joy from start to finish.",
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Silent Hill 2",
        genre: "action",
        platform: "PlayStation 5",
        status: "completed",
        favorite: false,
        hours_played: 16,
        rating: 4.6,
        price: "59.99",
        date_purchased: new Date("2025-06-05"),
        date_played: new Date("2025-06-06"),
        comment: "Remake exceeded all expectations.",
        cover_url: cover(2124490),
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    // --- Wishlist ---
    {
        user_id: userId,
        title: "Silksong",
        genre: "platformer",
        platform: "Nintendo Switch",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: "When it comes out...",
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "GTA VI",
        genre: "action",
        platform: "PlayStation 5",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Fable",
        genre: "role-playing",
        platform: "Xbox One",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: "Hoping the reboot is good.",
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Metroid Prime 4",
        genre: "shooter",
        platform: "Nintendo Switch",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
    {
        user_id: userId,
        title: "Avowed",
        genre: "role-playing",
        platform: "Xbox One",
        status: "wishlist",
        favorite: false,
        hours_played: null,
        rating: null,
        price: null,
        date_purchased: null,
        date_played: null,
        comment: null,
        cover_url: null,
        created_at: new Date(),
        updated_at: null,
        deleted_at: null,
    },
];

export const FAKE_OWNERS = {
    alice: "aaaaaaaaaaaaaaaaaaaaaaaa",
    bob: "bbbbbbbbbbbbbbbbbbbbbbbb",
    carol: "cccccccccccccccccccccccc",
    dave: "dddddddddddddddddddddddd",
    eve: "eeeeeeeeeeeeeeeeeeeeeeee",
    frank: "ffffffffffffffffffffffff",
    grace: "111111111111111111111111",
    henry: "222222222222222222222222",
    iris: "333333333333333333333333",
    jack: "444444444444444444444444",
    kate: "555555555555555555555555",
    liam: "666666666666666666666666",
    mia: "777777777777777777777777",
    noah: "888888888888888888888888",
    olivia: "999999999999999999999999",
};

export const clubs = (userId: string) => [
    {
        name: "Souls Collective",
        owner: userId,
        avatar_url: null,
        description:
            "For those who love punishment. We play one FromSoftware game at a time, together.",
        members: [userId, FAKE_OWNERS.alice, FAKE_OWNERS.bob, FAKE_OWNERS.grace, FAKE_OWNERS.iris],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Elden Ring",
            cover_url: cover(1245620),
            start_date: new Date("2026-05-01"),
            end_date: new Date("2026-06-30"),
        },
        past_games: [
            { title: "Dark Souls III", cover_url: cover(374320), end_date: new Date("2026-02-28") },
            { title: "Sekiro", cover_url: cover(814380), end_date: new Date("2025-11-30") },
        ],
        created_at: new Date("2025-09-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Indie Explorers",
        owner: userId,
        avatar_url: null,
        description: "We dig through the itch.io backlog so you don't have to.",
        members: [
            userId,
            FAKE_OWNERS.dave,
            FAKE_OWNERS.henry,
            FAKE_OWNERS.kate,
            FAKE_OWNERS.liam,
            FAKE_OWNERS.bob,
        ],
        visibility: "public",
        invite_code: null,
        current_game: null,
        past_games: [],
        created_at: new Date("2026-01-15"),
        updated_at: null,
        deleted_at: null,
    },

    // --- Dev user is a member but does not own ---

    {
        name: "RPG Fellowship",
        owner: FAKE_OWNERS.alice,
        avatar_url: null,
        description:
            "Deep stories, rich worlds, long save files. We work through one RPG at a time as a group.",
        members: [FAKE_OWNERS.alice, FAKE_OWNERS.bob, FAKE_OWNERS.carol, userId],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Baldur's Gate 3",
            cover_url: cover(1086940),
            start_date: new Date("2026-04-01"),
            end_date: new Date("2026-07-31"),
        },
        past_games: [
            { title: "Disco Elysium", cover_url: cover(632470), end_date: new Date("2026-01-31") },
            {
                title: "Metaphor: ReFantazio",
                cover_url: cover(1689550),
                end_date: new Date("2025-09-30"),
            },
        ],
        created_at: new Date("2025-06-10"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "The Completionists",
        owner: FAKE_OWNERS.bob,
        avatar_url: null,
        description: "100% or nothing. We don't move on until every achievement is unlocked.",
        members: [
            FAKE_OWNERS.alice,
            FAKE_OWNERS.bob,
            FAKE_OWNERS.carol,
            userId,
            FAKE_OWNERS.dave,
            FAKE_OWNERS.eve,
            FAKE_OWNERS.frank,
            FAKE_OWNERS.grace,
            FAKE_OWNERS.henry,
            FAKE_OWNERS.iris,
            FAKE_OWNERS.jack,
            FAKE_OWNERS.kate,
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Elden Ring",
            cover_url: cover(1245620),
            start_date: new Date("2026-03-01"),
            end_date: new Date("2026-06-30"),
        },
        past_games: [
            { title: "Hollow Knight", cover_url: cover(367520), end_date: new Date("2026-01-15") },
            { title: "Celeste", cover_url: cover(504230), end_date: new Date("2025-10-31") },
            { title: "Hades", cover_url: cover(1145360), end_date: new Date("2025-07-31") },
        ],
        created_at: new Date("2025-03-20"),
        updated_at: null,
        deleted_at: null,
    },

    // --- Dev user has NOT joined (Join button visible) ---

    {
        name: "Horror Hunters",
        owner: FAKE_OWNERS.carol,
        avatar_url: null,
        description: "We only play in the dark. One horror game per month, voted on by the group.",
        members: [
            FAKE_OWNERS.alice,
            FAKE_OWNERS.carol,
            FAKE_OWNERS.dave,
            FAKE_OWNERS.eve,
            FAKE_OWNERS.frank,
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Silent Hill 2",
            cover_url: cover(2124490),
            start_date: new Date("2026-05-15"),
            end_date: new Date("2026-06-15"),
        },
        past_games: [
            {
                title: "Resident Evil Village",
                cover_url: cover(1196590),
                end_date: new Date("2026-04-30"),
            },
        ],
        created_at: new Date("2025-10-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Racing League",
        owner: FAKE_OWNERS.alice,
        avatar_url: null,
        description:
            "Weekly time trials, weekend tournaments. Sim racers and arcade racers both welcome.",
        members: [FAKE_OWNERS.alice, FAKE_OWNERS.bob, FAKE_OWNERS.dave, FAKE_OWNERS.eve],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Forza Horizon 5",
            cover_url: cover(1551360),
            start_date: new Date("2026-05-01"),
            end_date: null,
        },
        past_games: [],
        created_at: new Date("2026-02-14"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Couch Co-op Crew",
        owner: FAKE_OWNERS.bob,
        avatar_url: null,
        description:
            "Split-screen, local multiplayer, online co-op — if you can play it together, we're playing it.",
        members: [FAKE_OWNERS.bob, FAKE_OWNERS.carol, FAKE_OWNERS.dave],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Split Fiction",
            cover_url: cover(2717700),
            start_date: new Date("2026-05-10"),
            end_date: new Date("2026-06-10"),
        },
        past_games: [
            { title: "Portal 2", cover_url: cover(620), end_date: new Date("2026-04-30") },
        ],
        created_at: new Date("2025-11-05"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Retro Revival",
        owner: FAKE_OWNERS.carol,
        avatar_url: null,
        description:
            "Going back to the classics. PS1, PS2, SNES, N64 — if it's older than 2005, it's on the list.",
        members: [FAKE_OWNERS.alice, FAKE_OWNERS.carol],
        visibility: "public",
        invite_code: null,
        current_game: null,
        past_games: [
            {
                title: "Resident Evil 4 (Original)",
                cover_url: null,
                end_date: new Date("2026-03-31"),
            },
            { title: "Shadow of the Colossus", cover_url: null, end_date: new Date("2025-12-31") },
            { title: "Ico", cover_url: null, end_date: new Date("2025-09-30") },
        ],
        created_at: new Date("2025-05-20"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "FPS Legends",
        owner: FAKE_OWNERS.alice,
        avatar_url: null,
        description: "Private squad for our weekly FPS sessions. Invite only.",
        members: [
            FAKE_OWNERS.alice,
            FAKE_OWNERS.bob,
            FAKE_OWNERS.dave,
            FAKE_OWNERS.eve,
            FAKE_OWNERS.frank,
            FAKE_OWNERS.grace,
        ],
        visibility: "private",
        invite_code: "FPS-7X2K",
        current_game: {
            title: "Hades II",
            cover_url: cover(1145350),
            start_date: new Date("2026-06-01"),
            end_date: null,
        },
        past_games: [],
        created_at: new Date("2026-03-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "The Long Game: For Players with No Quit in Them",
        owner: FAKE_OWNERS.bob,
        avatar_url: null,
        description: "We exclusively play games with 80+ hour runtimes. No short games allowed.",
        members: [FAKE_OWNERS.bob, FAKE_OWNERS.dave],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Red Dead Redemption 2",
            cover_url: cover(1174180),
            start_date: new Date("2026-04-15"),
            end_date: new Date("2026-08-31"),
        },
        past_games: [
            {
                title: "Baldur's Gate 3",
                cover_url: cover(1086940),
                end_date: new Date("2026-03-31"),
            },
        ],
        created_at: new Date("2025-12-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Open World Addicts",
        owner: FAKE_OWNERS.carol,
        avatar_url: null,
        description: "We lose ourselves in open worlds. The bigger the map the better.",
        members: [
            FAKE_OWNERS.alice,
            FAKE_OWNERS.bob,
            FAKE_OWNERS.carol,
            FAKE_OWNERS.dave,
            FAKE_OWNERS.eve,
            FAKE_OWNERS.frank,
            FAKE_OWNERS.grace,
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Cyberpunk 2077",
            cover_url: cover(1091500),
            start_date: new Date("2026-05-20"),
            end_date: null,
        },
        past_games: [
            {
                title: "Red Dead Redemption 2",
                cover_url: cover(1174180),
                end_date: new Date("2026-04-30"),
            },
            { title: "God of War", cover_url: cover(1593500), end_date: new Date("2025-12-31") },
        ],
        created_at: new Date("2025-04-15"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Roguelike Runners",
        owner: FAKE_OWNERS.alice,
        avatar_url: null,
        description:
            "Permanent death, procedural generation, one more run. Every week we share our best runs.",
        members: [FAKE_OWNERS.alice, FAKE_OWNERS.carol, FAKE_OWNERS.dave],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Hades II",
            cover_url: cover(1145350),
            start_date: new Date("2026-05-06"),
            end_date: null,
        },
        past_games: [
            { title: "Hades", cover_url: cover(1145360), end_date: new Date("2026-02-28") },
            { title: "Balatro", cover_url: cover(2379780), end_date: new Date("2025-11-30") },
        ],
        created_at: new Date("2025-08-10"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Puzzle Enthusiasts",
        owner: FAKE_OWNERS.bob,
        avatar_url: null,
        description:
            "Brain-melting puzzles only. We discuss solutions, compare times, and suffer together.",
        members: [FAKE_OWNERS.bob, FAKE_OWNERS.dave, FAKE_OWNERS.eve],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Portal 2",
            cover_url: cover(620),
            start_date: new Date("2026-05-25"),
            end_date: new Date("2026-06-25"),
        },
        past_games: [],
        created_at: new Date("2026-04-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Strategy & Tactics",
        owner: FAKE_OWNERS.carol,
        avatar_url: null,
        description: "Turn-based, real-time, 4X — if it requires a plan, we're interested.",
        members: [FAKE_OWNERS.alice, FAKE_OWNERS.carol],
        visibility: "public",
        invite_code: null,
        current_game: null,
        past_games: [
            { title: "Civilization VI", cover_url: null, end_date: new Date("2026-04-15") },
            { title: "XCOM 2", cover_url: null, end_date: new Date("2025-12-15") },
        ],
        created_at: new Date("2025-07-04"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Action RPG Alliance",
        owner: FAKE_OWNERS.alice,
        avatar_url: null,
        description: "The sweet spot between action and RPG. Fast combat, deep builds, great loot.",
        members: [
            FAKE_OWNERS.alice,
            FAKE_OWNERS.bob,
            FAKE_OWNERS.carol,
            FAKE_OWNERS.dave,
            FAKE_OWNERS.eve,
            FAKE_OWNERS.frank,
            FAKE_OWNERS.grace,
            FAKE_OWNERS.henry,
            FAKE_OWNERS.iris,
            FAKE_OWNERS.jack,
            FAKE_OWNERS.kate,
            FAKE_OWNERS.liam,
            FAKE_OWNERS.mia,
            FAKE_OWNERS.noah,
            FAKE_OWNERS.olivia,
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Monster Hunter Wilds",
            cover_url: cover(2246340),
            start_date: new Date("2026-03-15"),
            end_date: null,
        },
        past_games: [
            { title: "Elden Ring", cover_url: cover(1245620), end_date: new Date("2026-02-28") },
            { title: "God of War", cover_url: cover(1593500), end_date: new Date("2025-10-31") },
            { title: "Sekiro", cover_url: cover(814380), end_date: new Date("2025-06-30") },
        ],
        created_at: new Date("2024-11-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Narrative First",
        owner: FAKE_OWNERS.bob,
        avatar_url: null,
        description:
            "Gameplay is secondary. We're here for the writing, the characters, and the moments that stick with you.",
        members: [FAKE_OWNERS.bob, FAKE_OWNERS.carol, FAKE_OWNERS.dave, FAKE_OWNERS.eve],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "The Last of Us Part I",
            cover_url: cover(1888930),
            start_date: new Date("2026-05-01"),
            end_date: new Date("2026-06-30"),
        },
        past_games: [
            { title: "Disco Elysium", cover_url: cover(632470), end_date: new Date("2026-03-31") },
            {
                title: "Red Dead Redemption 2",
                cover_url: cover(1174180),
                end_date: new Date("2025-11-30"),
            },
        ],
        created_at: new Date("2025-02-14"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "The Backlog",
        owner: FAKE_OWNERS.carol,
        avatar_url: null,
        description:
            "Dedicated to finally finishing the games we bought and forgot about. No shame, only progress.",
        members: [FAKE_OWNERS.alice, FAKE_OWNERS.bob, FAKE_OWNERS.carol],
        visibility: "public",
        invite_code: null,
        current_game: null,
        past_games: [
            {
                title: "Cyberpunk 2077",
                cover_url: cover(1091500),
                end_date: new Date("2026-05-31"),
            },
            { title: "Stardew Valley", cover_url: cover(413150), end_date: new Date("2026-02-28") },
            { title: "Hades", cover_url: cover(1145360), end_date: new Date("2025-10-31") },
            { title: "Celeste", cover_url: cover(504230), end_date: new Date("2025-07-31") },
        ],
        created_at: new Date("2025-01-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Nintendo Nights",
        owner: FAKE_OWNERS.alice,
        avatar_url: null,
        description:
            "Nintendo exclusives only. We play through the Switch library one game at a time.",
        members: [FAKE_OWNERS.alice],
        visibility: "public",
        invite_code: null,
        current_game: null,
        past_games: [],
        created_at: new Date("2026-05-01"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Simulation Station",
        owner: FAKE_OWNERS.bob,
        avatar_url: null,
        description:
            "City builders, farming sims, life sims. If it simulates something, we're playing it.",
        members: [FAKE_OWNERS.bob, FAKE_OWNERS.dave, FAKE_OWNERS.eve, FAKE_OWNERS.frank],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Cities: Skylines",
            cover_url: cover(255710),
            start_date: new Date("2026-04-20"),
            end_date: null,
        },
        past_games: [
            { title: "Stardew Valley", cover_url: cover(413150), end_date: new Date("2026-03-31") },
        ],
        created_at: new Date("2025-09-15"),
        updated_at: null,
        deleted_at: null,
    },
    {
        name: "Soulslike & Chill",
        owner: FAKE_OWNERS.carol,
        avatar_url: null,
        description:
            "We appreciate the genre but we don't gatekeep. All skill levels welcome, summons encouraged.",
        members: [
            FAKE_OWNERS.alice,
            FAKE_OWNERS.carol,
            FAKE_OWNERS.dave,
            FAKE_OWNERS.eve,
            FAKE_OWNERS.frank,
            FAKE_OWNERS.grace,
            FAKE_OWNERS.henry,
        ],
        visibility: "public",
        invite_code: null,
        current_game: {
            title: "Lies of P",
            cover_url: null,
            start_date: new Date("2026-05-15"),
            end_date: new Date("2026-07-15"),
        },
        past_games: [
            { title: "Sekiro", cover_url: cover(814380), end_date: new Date("2026-04-30") },
            { title: "Dark Souls III", cover_url: cover(374320), end_date: new Date("2025-12-31") },
            { title: "Elden Ring", cover_url: cover(1245620), end_date: new Date("2025-08-31") },
        ],
        created_at: new Date("2025-05-01"),
        updated_at: null,
        deleted_at: null,
    },
];
